[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = '#2c2c2c'
foreground = '#d6d6d6'

dim_foreground    = '#dbdbdb'
bright_foreground = '#d9d9d9'

# Cursor colors
[colors.cursor]
text   = '#2c2c2c'
cursor = '#d9d9d9'

# Normal colors
[colors.normal]
black   = '#1c1c1c'
red     = '#bc5653'
green   = '#909d63'
yellow  = '#ebc17a'
blue    = '#7eaac7'
magenta = '#aa6292'
cyan    = '#86d3ce'
white   = '#cacaca'

# Bright colors
[colors.bright]
black   = '#636363'
red     = '#bc5653'
green   = '#909d63'
yellow  = '#ebc17a'
blue    = '#7eaac7'
magenta = '#aa6292'
cyan    = '#86d3ce'
white   = '#f7f7f7'

# Dim colors
[colors.dim]
black   = '#232323'
red     = '#74423f'
green   = '#5e6547'
yellow  = '#8b7653'
blue    = '#556b79'
magenta = '#6e4962'
cyan    = '#5c8482'
white   = '#828282'


[font]
size = 12.0

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[font.bold]
family = "FiraCode Nerd Font"
style = "bold"

[font.italic]
family = "FiraCode Nerd Font"
style = "italic"

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "BoldItalic"


[window]
opacity = 0.9

[window.padding]
x = 15
y = 15


[selection]
save_to_clipboard = true

[scrolling]
history = 10000
multiplier = 5

[terminal]

[terminal.shell]
program = "/run/current-system/sw/bin/fish"
